"use client";
/* eslint-disable @next/next/no-img-element */
import Link from "next/link";
import { BookmarkPlus, Compass } from "lucide-react";
import type { SemanticTab, WorldShiftListItem, WorldShiftSnapshot } from "@/types/worldShift";
import { getPersonaConfig, personas } from "@/config/personas";
export function AppHeader() { return <header className="news-masthead"><Link href="/" className="news-brand" aria-label="WorldTune home"><span className="wordmark"><span>WORLD</span><span>TUNE</span></span></Link><p>Understand the forces shaping the world</p><span>Independent context · Evidence linked</span></header>; }
export function WorldShiftStrip({ title }: { title: string; strength: number; snapshotId: string }) { return <div className="news-edition"><span>Today&apos;s world briefing</span><span>{title}</span><span>{new Date().toLocaleDateString(undefined, { weekday: "long", day: "numeric", month: "long" })}</span></div>; }
// The backend falls back to "Reporting related to {topic}" when GDELT gave
// no real headline (see world_shift_contract.py::_evidence). Never show that
// placeholder as if it were a real headline -- skip the entry instead.
function isPlaceholderTitle(title: string) { return title.trim().toLowerCase().startsWith("reporting related to"); }

export function LeftSidebar({ shifts, currentId, persona, tab }: { shifts: WorldShiftListItem[]; currentId: string; persona: string; tab: SemanticTab }) { return <aside className="order-2 space-y-8 xl:order-none"><section><p className="news-section-label">World Shifts</p><div className="news-topic-list">{shifts.map((shift) => <Link key={shift.id} href={`/world-shifts/${shift.id}?persona=${persona}&tab=${tab}`} data-current={shift.id === currentId}><span>{String(shift.rank).padStart(2, "0")}</span><strong>{shift.title}</strong>{shift.isTrending && <em className="ml-2 rounded bg-fuchsia-900/60 px-1.5 py-0.5 text-[10px] font-semibold uppercase tracking-wide text-fuchsia-200 not-italic">Trending</em>}</Link>)}</div></section><section><p className="news-section-label">Your perspective</p><div className="news-personas">{Object.values(personas).map((entry) => <Link key={entry.id} href={`/world-shifts/${currentId}?persona=${entry.id}&tab=${tab}`} data-current={entry.id === persona}>{entry.label}</Link>)}</div></section></aside>; }
export function RightSidebar({ data, tab }: { data: WorldShiftSnapshot; tab: SemanticTab }) { const related = data.shift.relatedShifts; const latest = data.evidence.filter((item) => !isPlaceholderTitle(item.title)).slice(0, 3); return <aside className="order-3 space-y-8"><section className="news-aside-lead"><p className="news-section-label">{tab === "forecast" ? "Forecast boundary" : "The short version"}</p><p>{tab === "forecast" ? data.whatHappensNext.framing : data.shift.overview.quickTake ?? data.shift.summary}</p></section>{tab === "evidence" ? <section><p className="news-section-label">Source note</p><p className="news-source-count">{data.evidence.length}</p><p className="muted">supporting records in this edition</p></section> : latest.length > 0 && <section><p className="news-section-label">Related reporting</p><div className="news-related-reporting">{latest.map((item) => <a key={item.id} href={item.url} target="_blank" rel="noreferrer" className="flex gap-3">{item.imageUrl && <img src={item.imageUrl} alt="" loading="lazy" referrerPolicy="no-referrer" className="h-12 w-16 shrink-0 rounded object-cover" />}<span className="flex flex-col"><span>{item.source}</span><strong>{item.title}</strong></span></a>)}</div></section>}<section><p className="news-section-label">Continue reading</p><div className="news-continue">{related.map((item) => <Link key={item.id} href={`/world-shifts/${item.id}?persona=${data.persona}&tab=overview`}><Compass size={13} /><span><strong>{item.title}</strong>{item.relationshipReason && <small>{item.relationshipReason}</small>}</span></Link>)}</div><button className="mt-5 flex items-center gap-2 text-xs font-medium text-slate-500 hover:text-white"><BookmarkPlus size={15} />Save this briefing</button></section></aside>; }
export function ShiftTabs({ persona, selected, onTab }: { persona: string; selected: SemanticTab; onTab: (tab: SemanticTab) => void }) { const config = getPersonaConfig(persona); return <nav className="flex overflow-x-auto border-b border-line">{(Object.keys(config.tabs) as SemanticTab[]).map((tab) => <button key={tab} data-active={tab === selected} className="tab whitespace-nowrap" onClick={() => onTab(tab)}>{config.tabs[tab]}</button>)}</nav>; }
