import { z } from "zod";
const direction = z.enum(["positive", "negative", "up", "down", "mixed", "neutral", "uncertain"]);
const confidence = z.enum(["low", "medium", "high"]);
const evidenceIds = z.array(z.string());
// "reasoned" = the AI connecting dots with world knowledge rather than
// restating the evidence corpus (see world_shift_ai.py). Must render with a
// visibly different treatment -- never merged visually with observed text.
const evidenceClass = z.enum(["observed", "calculated", "inferred", "associated", "reasoned"]);
const point = z.object({ text: z.string(), evidenceClass, evidenceIds, claimIds: z.array(z.string()).default([]) });
const optionalDirection = direction.nullable().optional();
const optionalMagnitude = z.enum(["low", "moderate", "medium", "high", "critical", "significant"]).nullable().optional();
const impact = z.object({ id: z.string(), title: z.string(), summary: z.string(), direction: optionalDirection, magnitude: optionalMagnitude, evidenceIds, claimIds: z.array(z.string()).default([]), evidenceClass: evidenceClass.default("inferred"), mechanism: z.string().nullable().optional(), horizon: z.enum(["immediate", "7d", "30d", "90d", "long_term"]).nullable().optional(), confidence: confidence.default("low"), counterEvidenceIds: z.array(z.string()).default([]), invalidators: z.array(z.string()).default([]), reasoning: z.array(z.string()).default([]), derivedFrom: z.array(z.string()).default([]), verificationHint: z.string().nullable().optional() });
// A reasoned, never-observed company exposure: "which companies get
// impacted, and why". entityName is often NOT in the GDELT corpus by design.
const exposureItem = z.object({ id: z.string(), entityName: z.string(), ticker: z.string().nullable().optional(), direction: z.enum(["positive", "negative", "mixed"]), ring: z.enum(["direct", "supply_chain", "second_order"]), mechanism: z.string(), reasoning: z.array(z.string()).default([]), confidence: confidence.default("low"), derivedFrom: z.array(z.string()).default([]), verificationHint: z.string().nullable().optional(), horizons: z.array(z.enum(["near_term", "long_term"])).default([]), countries: z.array(z.string()).default([]), opportunityType: z.string().nullable().optional(), evidenceIds: z.array(z.string()).default([]), evidenceClass: z.literal("reasoned").default("reasoned") });
const evidence = z.object({ id: z.string(), type: z.string(), source: z.string(), title: z.string(), summary: z.string().nullish().transform((x) => x ?? undefined), publishedAt: z.string(), url: z.string(), imageUrl: z.string().nullable().optional(), entities: z.array(z.string()), tags: z.array(z.string()), relationshipRole: z.string().nullish().transform((x) => x ?? undefined), confidence, supports: z.array(z.string()), sourceDomain: z.string().nullable().optional(), originalHeadline: z.string().nullable().optional(), sourceSnippet: z.string().nullable().optional(), aiSummary: z.string().nullable().optional(), eventIds: z.array(z.string()).default([]), claimIds: z.array(z.string()).default([]), entityIds: z.array(z.string()).default([]), evidenceClass: evidenceClass.default("observed"), sourceClass: z.enum(["primary", "secondary", "aggregator", "unknown"]).default("unknown"), retrievalStatus: z.enum(["complete", "metadata_only", "unavailable"]).default("metadata_only"), publisherFamily: z.string().nullable().optional(), independentPublisherCount: z.number().default(1), corroborationStatus: z.enum(["single_source", "syndicated", "independently_corroborated", "contested"]).default("single_source") });
const snapshotMeta = z.object({ snapshotId: z.string(), generatedAt: z.string(), validUntil: z.string() });
const listItem = z.object({ id: z.string(), title: z.string(), rank: z.number(), status: z.enum(["surging", "rising", "changing", "watching", "stable", "declining", "elevated"]), direction, relationshipReason: z.string().nullable().optional(), relationshipConfidence: confidence.nullable().optional(), isTrending: z.boolean().default(false) });
const relationships = z.object({ nodes: z.array(z.object({ id: z.string(), label: z.string(), type: z.string(), category: z.string().nullable().optional(), summary: z.string().nullable().optional(), direction: optionalDirection, magnitude: optionalMagnitude, evidenceIds })), edges: z.array(z.object({ id: z.string(), source: z.string(), target: z.string(), relationship: z.string(), category: z.string().nullable().optional(), explanation: z.string().nullable().optional(), confidence, evidenceIds, claimIds: z.array(z.string()).default([]), evidenceClass: evidenceClass.default("associated"), mechanism: z.string().nullable().optional(), temporalOrder: z.string().nullable().optional(), opposingEvidenceIds: z.array(z.string()).default([]), alternativeExplanations: z.array(z.string()).default([]), firstObservedAt: z.string().nullable().optional(), lastUpdatedAt: z.string().nullable().optional() })), story: z.record(z.string().nullable()).optional(), crossShiftLinks: z.array(z.object({ shiftId: z.string(), title: z.string(), relationship: z.string(), explanation: z.string(), confidence, evidenceClass: z.enum(["inferred", "associated"]), evidenceIds, indicators: z.array(z.string()) })).default([]), personalPaths: z.array(z.object({ id: z.string(), title: z.string(), persona: z.string(), steps: z.array(z.string()), explanation: z.string(), confidence, evidenceIds })).default([]) });
const scenario = z.object({ id: z.string(), label: z.enum(["base", "upside", "downside"]), title: z.string(), summary: z.string(), horizon: z.enum(["7d", "30d", "90d"]), confidence, triggers: z.array(z.string()), indicators: z.array(z.string()), invalidators: z.array(z.string()), implications: z.array(z.string()), evidenceIds, evidenceClass: z.literal("inferred").default("inferred") });
const whatHappensNext = z.object({ generatedAt: z.string(), evidenceCutoff: z.string(), model: z.string(), promptVersion: z.string(), framing: z.string(), scenarios: z.array(scenario), resolutionStatus: z.enum(["open", "resolved", "expired"]) });
export const worldShiftListResponseSchema = snapshotMeta.extend({ entries: z.array(listItem) });
export const relationshipsResponseSchema = snapshotMeta.extend({ relationships });
export const evidenceResponseSchema = snapshotMeta.extend({ evidence: z.array(evidence) });
export const worldShiftSnapshotSchema = snapshotMeta.extend({ schemaVersion: z.string().default("1.0"), persona: z.string(), shift: z.object({ id: z.string(), title: z.string(), summary: z.string(), status: z.enum(["surging", "rising", "changing", "watching", "stable", "declining", "elevated"]), direction, signalStrength: z.number(), updatedAt: z.string(), overview: z.object({ whatHappened: z.string(), whyItMatters: z.string(), quickTake: z.string().optional(), characteristics: z.array(z.string()), themes: z.array(z.string()), whatsHappening: z.array(point).default([]), whyItMattersPoints: z.array(point).default([]), keyDevelopments: z.array(point).default([]), watchNext: z.array(point).default([]), drivers: z.array(point).default([]), contradictions: z.array(point).default([]), contextBrief: z.object({ whatItIs: z.string(), howItStarted: z.string(), latest: z.string(), whatItIsEvidenceIds: z.array(z.string()).default([]), howItStartedEvidenceIds: z.array(z.string()).default([]), latestEvidenceIds: z.array(z.string()).default([]) }).nullish().transform((x) => x ?? undefined), timeline: z.array(z.object({ date: z.string(), title: z.string(), summary: z.string(), status: z.enum(["confirmed", "reported", "claimed", "disputed"]), evidenceIds })).default([]), actors: z.array(z.object({ name: z.string(), role: z.string(), position: z.string(), status: z.enum(["confirmed", "reported", "claimed", "disputed"]), evidenceIds })).default([]), factsAndFigures: z.array(z.object({ value: z.string(), label: z.string(), context: z.string(), evidenceIds })).default([]), timelineKicker: z.string().nullable().optional(), timelineHeading: z.string().nullable().optional() }), relatedShifts: z.array(listItem), isTrending: z.boolean().default(false) }), content: z.object({ impact: z.object({ summary: z.string(), directImpacts: z.array(impact), impactChain: z.array(impact), secondOrderEffects: z.array(impact), opportunities: z.array(impact), risks: z.array(impact), watchItems: z.array(impact), exposureMap: z.array(exposureItem).default([]), kicker: z.string().nullable().optional(), headline: z.string().nullable().optional(), exposureHeadline: z.string().nullable().optional(), exposureBlurb: z.string().nullable().optional(), lensTitle: z.string().nullable().optional(), lensBlurb: z.string().nullable().optional() }), domain: z.object({ groups: z.array(z.object({ id: z.string(), title: z.string(), entityType: z.string().optional(), items: z.array(z.object({ id: z.string(), name: z.string(), type: z.string(), direction: optionalDirection, magnitude: optionalMagnitude, summary: z.string(), evidenceIds })) })) }) }), relationships, evidence: z.array(evidence), whatHappensNext });
export const refreshStatusSchema = z.object({ runId: z.string(), status: z.enum(["queued", "running", "completed", "failed"]), stage: z.string(), progress: z.object({ completed: z.number(), total: z.number() }), currentSnapshotId: z.string().nullable().optional(), newSnapshotId: z.string().nullable().optional(), error: z.string().nullable().optional() });
export const refreshConfigurationSchema = z.object({ intervalSeconds: z.number(), webResearchEnabled: z.boolean(), webResultsPerShift: z.number(), allowedIntervals: z.array(z.number()), nextRefreshAt: z.string().nullable().optional() });
